### ISSUE TITLE
Deployment to Bluemix fails

### ISSUE THREAD

**Issue by dnh-ee** [jroyal/SlackPoll#17]
I got the following error when following the setup instructions:

```
FAILED
Could not find service cloudant-slackpoll to bind to app
```

Is there a service that this depends upon that is no longer running?

Full logs:

Started by user pipeline
Building remotely on jenkins-deploy-slave-495e3f7a41e3 (.*Deploy) in workspace /home/jenkins/workspace/881fa63f-84ac-f31e-2889-13a4b11a689c/412ee33b-0e0b-4470-adf8-c2578d586adb
Unable to access upstream artifacts area /jenkins/jobs/881fa63f-84ac-f31e-2889-13a4b11a689c/jobs/f4ae2ad6-c435-47f2-8582-4dace9663ef5/builds/2015-06-12_02-26-35/archive. Does source project archive artifacts?
Downloading artifacts ...
DOWNLOAD SUCCESSFUL
Total time: 1 seconds
[412ee33b-0e0b-4470-adf8-c2578d586adb] $ /bin/bash /tmp/hudson6323955784770894451.sh
- cat /etc/lsb-release /etc/os-release
  DISTRIB_ID=Ubuntu
  DISTRIB_RELEASE=14.04
  DISTRIB_CODENAME=trusty
  DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"
  NAME="Ubuntu"
  VERSION="14.04.2 LTS, Trusty Tahr"
  ID=ubuntu
  ID_LIKE=debian
  PRETTY_NAME="Ubuntu 14.04.2 LTS"
  VERSION_ID="14.04"
  HOME_URL="http://www.ubuntu.com/"
  SUPPORT_URL="http://help.ubuntu.com/"
  BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
- cf --version
  /usr/bin/cf-orig/cf version 6.7.0-IDS-2014-12-04T10:56:46+00:00
- echo 'Target: https://api.eu-gb.bluemix.net'
  Target: https://api.eu-gb.bluemix.net
- source _deploy.sh
  ++ cf push app-nnn-nnn
  Using manifest file /home/jenkins/workspace/881fa63f-84ac-f31e-2889-13a4b11a689c/412ee33b-0e0b-4470-adf8-c2578d586adb/manifest.yml

Creating app app-nnn-nnn in org nnn@nnn / space dev as nnn@nnn...
OK

Using route app-nnn-nnn.eu-gb.mybluemix.net
Binding app-nnn-nnn.eu-gb.mybluemix.net to app-nnn-nnn...
OK

Uploading app-nnn-nnn...
Uploading app files from: /home/jenkins/workspace/881fa63f-84ac-f31e-2889-13a4b11a689c/412ee33b-0e0b-4470-adf8-c2578d586adb
Uploading 80.1K, 12 files

Done uploading
OK
FAILED
Could not find service cloudant-slackpoll to bind to app-nnn-nnn
Build step 'Execute shell' marked build as failure

**Comment by jroyal** [comment]
Hey sorry this has taken so long for me to get back too, but I ended up getting super busy at work and I forgot. For now, I have removed the adding to Bluemix section. I was having difficulties getting that too work after you mentioned it as well, so I moved to using docker. I would suggest giving that a try if you still want to use this.
