### ISSUE TITLE
Doesn't work on Heroku

### ISSUE THREAD

**Issue by NapalmCodes** [jroyal/SlackPoll#20]
When attempting to deploy on heroku it is complaining as follows:

$ heroku docker:start
!     Error: Procfile required. Aborting

I am guessing the target was never intended to be Heroku, but is there any plan to do this?

**Comment by jroyal** [comment]
I haven't ever tried to deploy to heroku, and I'm not sure what work would need to be done to allow it. As I get time, i'll look into it. If you figure it out before I do, let me know!

**Comment by NapalmCodes** [comment]
I feel like I am very close as the application will spin up locally for me showing the page "The voting machine is up and running."  However, I am unable to point slack to it locally (my guess is firewall settings prevent it from going out and coming back in).  So I deployed and sill get an application error when hitting the URL after a successful deploy (per heroku docker:release):

`←[32m2015-07-22T19:35:17.151610+00:00 heroku[router]:←[0m at=error code=H10 desc
="App crashed" method=GET path="/favicon.ico" host=myappname.herokuapp.com request_id=78abcb56-2408-41ef-acca-25cd52890f07 fwd="<ip address>" dyno= connect
= service= status=503 bytes=`

If it helps I created a simple Procfile in the root directory with the line:

`web: gunicorn slack-poll:app --log-file=-`

I also updated the Dockerfile with the following line `RUN pip install gunicorn`

Hope this information is helpful to someone as we have resorted to using Subcurrent temporarily.
